In [5]:
import numpy as np
import pandas as pd

In [6]:
import math

In [7]:
boundaries = np.load('full_boundaries.npy')

In [72]:
boundaries_1b = np.load('boundaries_1b.npy')

In [76]:
boundaries_1b_s =  boundaries_1b[boundaries[:,0].argsort()]

In [79]:
boundaries_1b_s[0:10]

array([[  3.  ,   7.69,  12.52,   4.83,  -5.62,  -5.51],
       [  4.  ,  12.52,  15.65,   3.13,  -5.51,  -5.1 ],
       [  6.  ,  18.35,  21.24,   2.89,  -4.92,  -4.92],
       [  7.  ,  21.24,  23.2 ,   1.96,  -4.92,  -4.69],
       [  9.  ,  25.16,  27.51,   2.35,  -4.22,  -4.22],
       [ 13.  ,  36.31,  38.52,   2.21,  -4.04,  -3.81],
       [ 14.  ,  38.52,  43.75,   5.22,  -3.81,  -3.75],
       [ 29.  , 138.71, 143.43,   4.72,  -3.4 ,  -3.16],
       [ 30.  , 143.43, 146.66,   3.23,  -3.16,  -3.11],
       [ 72.  , 283.  , 285.45,   2.46,  -1.41,  -1.05]])

In [78]:
boundaries[0:10]

array([[  3.  ,   7.39,  11.49,   4.1 ,  -5.62,  -5.51],
       [  4.  ,  11.49,  13.84,   2.35,  -5.51,  -5.1 ],
       [  6.  ,  15.99,  18.7 ,   2.71,  -4.92,  -4.92],
       [  7.  ,  18.7 ,  21.15,   2.45,  -4.92,  -4.69],
       [  9.  ,  23.36,  26.06,   2.7 ,  -4.22,  -4.22],
       [ 13.  ,  35.02,  45.24,  10.22,  -4.04,  -3.81],
       [ 14.  ,  45.24,  47.22,   1.98,  -3.81,  -3.75],
       [ 29.  , 110.6 , 113.9 ,   3.3 ,  -3.4 ,  -3.16],
       [ 30.  , 113.9 , 115.86,   1.96,  -3.16,  -3.11],
       [ 72.  , 230.51, 239.83,   9.32,  -1.41,  -1.05]])

In [8]:
np.set_printoptions(precision=2)
np.set_printoptions(suppress=True)

In [12]:
def convert_boundaries_to_clusters(boundaries:np.array) -> np.array:
    n_boundaries = boundaries.shape[0]
    n_clusters = math.ceil(n_boundaries/2)
    clusters = np.zeros((n_clusters, 3))
    j = 0
    for i in range(0, n_boundaries, 2):
        pt_low = boundaries[i,1]
        pt_high = boundaries[i+1, 2]
        pt_sum = pt_high - pt_low
        z0_low = boundaries[i, 4]
        z0_high = boundaries[i+1, 5]

        clusters[j,0] = pt_sum
        clusters[j, 1] = z0_low
        clusters[j, 2] = z0_high
        j+=1
    return clusters

In [13]:
clusters = convert_boundaries_to_clusters(boundaries)

In [14]:
clusters

array([[  6.45,  -5.62,  -5.1 ],
       [  5.16,  -4.92,  -4.69],
       [ 21.88,  -4.22,  -3.81],
       [ 68.66,  -3.81,  -3.16],
       [125.93,  -3.16,  -1.05],
       [ 10.82,  -1.05,  -0.76],
       [ 17.85,  -0.59,  -0.12],
       [ 87.52,  -0.12,   0.59],
       [  4.55,   0.59,   0.88],
       [  7.32,   0.88,   1.29],
       [  4.15,   1.29,   1.64],
       [  4.58,   1.64,   1.99],
       [  5.41,   1.99,   2.29],
       [  4.51,   2.46,   2.81],
       [ 16.5 ,   2.81,   3.46],
       [ 10.25,   3.46,   3.87],
       [  6.36,   3.87,   4.04],
       [  4.39,   5.27,   5.74],
       [ 10.18,   5.74,   6.5 ],
       [ 12.81,   6.5 ,   7.03],
       [  0.  ,  21.  ,   0.  ],
       [  0.  ,  21.  ,  21.  ],
       [  0.  ,  21.  ,  21.  ],
       [  0.  ,  21.  ,  21.  ],
       [  0.  ,  21.  ,  21.  ],
       [  0.  ,  21.  ,  21.  ],
       [  0.  ,  21.  ,  21.  ],
       [  0.  ,  21.  ,  21.  ],
       [  0.  ,  21.  ,  21.  ],
       [  0.  ,  21.  ,  21.  ],
       [  

In [15]:
boundaries_b = np.load('boundaries.npy')

In [18]:
boundaries_b

array([[  2.  ,   5.25,  10.48,   5.22,  -3.81,  -3.75],
       [  3.  ,  10.48,  12.61,   2.14,  -3.75,  -2.81],
       [  4.  ,  12.61,  15.02,   2.41,  -2.81,  -2.7 ],
       [  5.  ,  15.02,  17.08,   2.06,  -2.7 ,  -2.46],
       [  7.  ,  20.55,  22.83,   2.29,  -2.29,  -2.29],
       [  8.  ,  22.83,  25.78,   2.95,  -2.29,  -1.76],
       [  9.  ,  25.78,  28.72,   2.94,  -1.76,  -1.76],
       [ 11.  ,  39.36,  41.46,   2.1 ,  -1.7 ,  -1.46],
       [ 12.  ,  41.46,  43.77,   2.31,  -1.46,  -1.41],
       [ 13.  ,  43.77,  46.29,   2.53,  -1.41,  -1.  ],
       [ 15.  ,  49.34,  51.85,   2.51,  -0.59,  -0.53],
       [ 17.  ,  55.53,  57.7 ,   2.17,  -0.41,  -0.06],
       [ 18.  ,  57.7 ,  60.69,   2.99,  -0.06,   0.06],
       [ 20.  ,  63.24,  65.42,   2.18,   0.12,   0.29],
       [ 21.  ,  65.42,  67.51,   2.09,   0.29,   0.35],
       [ 24.  ,  71.95,  74.31,   2.36,   0.35,   1.  ],
       [ 29.  ,  83.59,  86.82,   3.23,   2.46,   2.52],
       [ 30.  ,  86.82,  91.01,

In [19]:
clusters_b = convert_boundaries_to_clusters(boundaries_b)

In [29]:
clusters_b

array([[ 7.36, -3.81, -2.81],
       [ 4.47, -2.81, -2.46],
       [ 5.23, -2.29, -1.76],
       [15.68, -1.76, -1.46],
       [ 4.83, -1.46, -1.  ],
       [ 8.36, -0.59, -0.06],
       [ 7.72, -0.06,  0.29],
       [ 8.89,  0.29,  1.  ],
       [ 7.43,  2.46,  2.93],
       [ 9.48,  2.93,  3.46],
       [ 0.  , 21.  ,  0.  ],
       [ 0.  , 21.  , 21.  ],
       [ 0.  , 21.  , 21.  ],
       [ 0.  , 21.  , 21.  ],
       [ 0.  , 21.  , 21.  ],
       [ 0.  , 21.  , 21.  ],
       [ 0.  , 21.  , 21.  ],
       [ 0.  , 21.  , 21.  ],
       [ 0.  , 21.  , 21.  ],
       [ 0.  , 21.  , 21.  ],
       [ 0.  , 21.  , 21.  ],
       [ 0.  , 21.  , 21.  ],
       [ 0.  , 21.  , 21.  ],
       [ 0.  , 21.  , 21.  ],
       [ 0.  , 21.  , 21.  ]])

In [22]:
columns = ['idx', 'pt_min', 'pt_max','pt_sum','z0_min','z0_max']

In [23]:
df = pd.DataFrame(boundaries_b, columns=columns)

In [28]:
df['z0_max']. - df['z0_min']

0           NaN
1      0.000000
2      0.000000
3      0.000000
4     -0.175781
5      0.000000
6      0.000000
7     -0.058594
8      0.000000
9      0.000000
10    -0.410156
11    -0.117188
12     0.000000
13    -0.058594
14     0.000000
15     0.000000
16    -1.464844
17     0.000000
18     0.000000
19    -0.117188
20   -17.542969
21    21.000000
22   -21.000000
23     0.000000
24     0.000000
25     0.000000
26     0.000000
27     0.000000
28     0.000000
29     0.000000
30     0.000000
31     0.000000
32     0.000000
33     0.000000
34     0.000000
35     0.000000
36     0.000000
37     0.000000
38     0.000000
39     0.000000
40     0.000000
41     0.000000
42     0.000000
43     0.000000
44     0.000000
45     0.000000
46     0.000000
47     0.000000
48     0.000000
49     0.000000
dtype: float64

In [21]:
boundaries_b

array([[  2.  ,   5.25,  10.48,   5.22,  -3.81,  -3.75],
       [  3.  ,  10.48,  12.61,   2.14,  -3.75,  -2.81],
       [  4.  ,  12.61,  15.02,   2.41,  -2.81,  -2.7 ],
       [  5.  ,  15.02,  17.08,   2.06,  -2.7 ,  -2.46],
       [  7.  ,  20.55,  22.83,   2.29,  -2.29,  -2.29],
       [  8.  ,  22.83,  25.78,   2.95,  -2.29,  -1.76],
       [  9.  ,  25.78,  28.72,   2.94,  -1.76,  -1.76],
       [ 11.  ,  39.36,  41.46,   2.1 ,  -1.7 ,  -1.46],
       [ 12.  ,  41.46,  43.77,   2.31,  -1.46,  -1.41],
       [ 13.  ,  43.77,  46.29,   2.53,  -1.41,  -1.  ],
       [ 15.  ,  49.34,  51.85,   2.51,  -0.59,  -0.53],
       [ 17.  ,  55.53,  57.7 ,   2.17,  -0.41,  -0.06],
       [ 18.  ,  57.7 ,  60.69,   2.99,  -0.06,   0.06],
       [ 20.  ,  63.24,  65.42,   2.18,   0.12,   0.29],
       [ 21.  ,  65.42,  67.51,   2.09,   0.29,   0.35],
       [ 24.  ,  71.95,  74.31,   2.36,   0.35,   1.  ],
       [ 29.  ,  83.59,  86.82,   3.23,   2.46,   2.52],
       [ 30.  ,  86.82,  91.01,

In [20]:
clusters_b

array([[ 7.36, -3.81, -2.81],
       [ 4.47, -2.81, -2.46],
       [ 5.23, -2.29, -1.76],
       [15.68, -1.76, -1.46],
       [ 4.83, -1.46, -1.  ],
       [ 8.36, -0.59, -0.06],
       [ 7.72, -0.06,  0.29],
       [ 8.89,  0.29,  1.  ],
       [ 7.43,  2.46,  2.93],
       [ 9.48,  2.93,  3.46],
       [ 0.  , 21.  ,  0.  ],
       [ 0.  , 21.  , 21.  ],
       [ 0.  , 21.  , 21.  ],
       [ 0.  , 21.  , 21.  ],
       [ 0.  , 21.  , 21.  ],
       [ 0.  , 21.  , 21.  ],
       [ 0.  , 21.  , 21.  ],
       [ 0.  , 21.  , 21.  ],
       [ 0.  , 21.  , 21.  ],
       [ 0.  , 21.  , 21.  ],
       [ 0.  , 21.  , 21.  ],
       [ 0.  , 21.  , 21.  ],
       [ 0.  , 21.  , 21.  ],
       [ 0.  , 21.  , 21.  ],
       [ 0.  , 21.  , 21.  ]])

In [34]:
clusters = []
for i in range(7):
    cn = np.load(f"clusters_b{i}.npy")
    clusters.append(cn)

In [35]:
len(clusters)

7

In [36]:
c1 = clusters[0]

In [38]:
c2 = clusters[1]

In [42]:
cs = np.vstack((c1,c2))

In [66]:
cs

array([[ 0.  ,  0.  ,  0.  ,  4.33, -4.04, -3.69],
       [ 0.  ,  0.  ,  0.  ,  9.06, -2.23, -2.05],
       [ 0.  ,  0.  ,  0.  ,  6.25, -0.41,  0.29],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  4.85, -4.92, -4.69],
       [ 0.  ,  0.  ,  0.  , 23.11, -3.69, -3.05],
       [ 0.  ,  0.  ,  0.  ,  9.85, -2.23, -1.99],
       [ 0.  ,  0.  ,  0.  ,  4.15,  6.5 ,  7.03],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  0

In [67]:
cs

array([[ 0.  ,  0.  ,  0.  ,  4.33, -4.04, -3.69],
       [ 0.  ,  0.  ,  0.  ,  9.06, -2.23, -2.05],
       [ 0.  ,  0.  ,  0.  ,  6.25, -0.41,  0.29],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  4.85, -4.92, -4.69],
       [ 0.  ,  0.  ,  0.  , 23.11, -3.69, -3.05],
       [ 0.  ,  0.  ,  0.  ,  9.85, -2.23, -1.99],
       [ 0.  ,  0.  ,  0.  ,  4.15,  6.5 ,  7.03],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  0

In [68]:
def merge_clusters(c_in):
    clusters = c_in.copy()
    max_pt = 0
    max_pt_i = 0
    merge_count = 0

    for i in range(clusters.shape[0]):
        if clusters[i, 4]>=21:
            continue

        if max_pt < clusters[i, 3]:
            max_pt = clusters[i, 3]
            max_pt_i = i
        for j in range(clusters.shape[0]):
            if clusters[j, 4]>=21:
                continue
            if i >= j:
                continue

            
            case1 = (clusters[i, 4] - 0.15) <= clusters[j, 5]
            case2 = (clusters[i, 5] + 0.15) >= clusters[j, 4]

            # case1 = (clusters[j, 4] <= clusters[i, 5] + 0.15) and (clusters[j, 5] <= clusters[i, 4] - 0.15)

            # case2 = (clusters[j, 5] >= clusters[i, 4] - 0.15) and (clusters[j, 4] <= clusters[i, 5] + 0.15)
            if case1 and case2:
                merge_count+=1
                if clusters[j, 4] < clusters[i, 4]:
                    clusters[i, 4] = clusters[j, 4]
                if clusters[j, 5] > clusters[i, 5]:
                    clusters[i, 5] = clusters[j, 5]
                clusters[i, 3] += clusters[j, 3]
                if max_pt < clusters[i, 3]:
                    max_pt = clusters[i, 3]
                    max_pt_i = i
                clusters[j, 3] = 0
                clusters[j, 4] = 21
                clusters[j, 5] = 21
    print(merge_count)
    return clusters
    

In [69]:
c_m = merge_clusters(cs)

2


In [70]:
c_m

array([[ 0.  ,  0.  ,  0.  , 27.44, -4.04, -3.05],
       [ 0.  ,  0.  ,  0.  , 18.91, -2.23, -1.99],
       [ 0.  ,  0.  ,  0.  ,  6.25, -0.41,  0.29],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  4.85, -4.92, -4.69],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  4.15,  6.5 ,  7.03],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  0

In [ ]:
        max_pt = 0
        max_pt_i = 0
        merge_count = 0
        for i in range(clusters.shape[0]):
            if max_pt < clusters[i, 3]:
                max_pt = clusters[i, 3]
                max_pt_i = i
            for j in range(clusters.shape[0]):

                if i >= j:
                    continue

                case1 = (clusters[j, 4] <= (clusters[i, 5] + self.eps)) and (
                    clusters[j, 5] <= (clusters[i, 4] - self.eps)
                )
                case2 = (clusters[j, 5] >= (clusters[i, 4] - self.eps)) and (
                    clusters[j, 4] <= (clusters[i, 5] + self.eps)
                )

                if case1 or case2:
                    # print("merging")
                    merge_count += 1
                    if clusters[j, 4] < clusters[i, 4]:
                        clusters[i, 4] = clusters[j, 4]
                    if clusters[j, 5] > clusters[i, 5]:
                        clusters[i, 5] = clusters[j, 5]
                    clusters[i, 3] += clusters[j, 3]
                    if max_pt < clusters[i, 3]:
                        max_pt = clusters[i, 3]
                        max_pt_i = i

In [33]:
clusters[1]

array([[ 0.  ,  0.  ,  0.  ,  4.85, -4.92, -4.69],
       [ 0.  ,  0.  ,  0.  , 23.11, -3.69, -3.05],
       [ 0.  ,  0.  ,  0.  ,  9.85, -2.23, -1.99],
       [ 0.  ,  0.  ,  0.  ,  4.15,  6.5 ,  7.03],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  , 21.  , 21.  ]])