In [1]:
%load_ext lab_black

In [2]:
import numpy as np
import math
import pandas as pd
import itertools
import copy
from sklearn.cluster import DBSCAN

In [130]:
pd.set_option("display.max_rows", None)

In [3]:
np.random.seed(42)

In [4]:
np.set_printoptions(precision=2)
np.set_printoptions(suppress=True)

In [132]:
z0_file = "/media/lucas/QS/binaries-trk/OldKF_TTbar_170K_quality-0-trk-z0.bin"
pt_file = "/media/lucas/QS/binaries-trk/OldKF_TTbar_170K_quality-0-trk-pt.bin"
z0 = np.fromfile(z0_file, dtype=np.float32)
pt = np.fromfile(pt_file, dtype=np.float32)

In [133]:
df = pd.DataFrame({"z0": z0, "pt": pt})

In [134]:
db = DBSCAN(eps=0.15, min_samples=2).fit(z0.reshape(-1, 1))

In [135]:
label = db.labels_

In [136]:
df["label"] = label

In [137]:
df["noise"] = 0

In [138]:
df.loc[df.label == -1, "noise"] = 1

In [139]:
df.noise.value_counts()

0    147
1     12
Name: noise, dtype: int64

In [140]:
df.head()

z0        pt  label  noise
0 -0.878906  2.623967      0      0
1  3.339844  3.435026      1      0
2  4.921875  3.774908      2      0
3 -0.468750  2.641448      3      0
4  4.980469  2.320653      2      0

In [141]:
df.sort_values(by="z0", inplace=True)

In [142]:
df

z0         pt  label  noise
67  -7.441406   2.149052     15      0
140 -7.441406   2.573483     15      0
76  -6.972656   3.295341     -1      1
153 -6.562500   3.295341     18      0
119 -6.503906   3.310079     18      0
135 -6.328125   2.251928     12      0
57  -6.328125   2.309069     12      0
62  -6.269531   2.014883     12      0
43  -6.152344   3.104588     12      0
147 -6.035156   1.980026     12      0
34  -5.332031   4.871437      9      0
51  -5.214844   2.100663      9      0
27  -5.156250   3.778763      9      0
81  -5.039062   4.026843      9      0
126 -4.980469   2.308109      9      0
115 -4.921875   2.349133      9      0
29  -4.863281   1.959754      9      0
118 -4.453125   2.302843     -1      1
149 -4.218750   2.707806     14      0
60  -4.160156   2.195374     14      0
96  -4.160156   2.499326     14      0
83  -4.101562   2.414004     14      0
84  -4.042969   2.229318     14      0
77  -3.808594   2.410335      5      0
125 -3.750000   2.053645      5      0
143 -3.750000   2.604270      5      0
93  -3.691406   2.442685      5      0
21  -3.632812   4.641306      5      0
8   -3.632812   5.702108      5      0
87  -3.574219   2.190609      5      0
64  -3.515625   2.666188      5      0
129 -3.281250   2.077082      8      0
35  -3.222656   4.105771      8      0
91  -3.164062   2.189745      8      0
66  -3.105469   2.812058      8      0
46  -3.046875   2.335789      8      0
61  -3.046875   2.537021      8      0
157 -3.046875   2.563973      8      0
22  -2.988281   3.104588      8      0
72  -2.988281   4.360568      8      0
104 -2.871094   2.206719      8      0
70  -2.812500   2.332354      8      0
90  -2.753906   2.232008      8      0
122 -2.753906   4.518521      8      0
71  -2.460938   2.997302     13      0
58  -2.460938   2.185434     13      0
73  -2.402344   2.602439     13      0
14  -2.226562   2.978006      6      0
134 -2.167969   1.996763      6      0
123 -2.050781   2.006870      6      0
120 -1.992188   2.202342      6      0
28  -1.992188   4.492920      6      0
56  -1.992188   2.014883      6      0
121 -1.992188   2.229766      6      0
139 -1.933594   2.516320      6      0
19  -1.933594   3.157567      6      0
69  -1.875000   2.886637      6      0
12  -1.875000   3.127325      6      0
114 -1.816406   2.673893      6      0
102 -1.816406   2.910093      6      0
131 -1.757812   1.961138      6      0
82  -1.757812   2.207597      6      0
30  -1.699219   2.448611      6      0
9   -1.640625   3.201270      6      0
80  -1.640625   2.015249      6      0
86  -1.640625   2.015249      6      0
132 -1.347656   2.881392      0      0
136 -1.347656   1.993536      0      0
98  -1.289062   4.164293      0      0
113 -1.289062   2.288601      0      0
17  -1.171875   3.305152      0      0
101 -1.113281   2.785949      0      0
10  -1.113281   2.752108      0      0
13  -1.113281   2.358616      0      0
59  -1.054688   2.635178      0      0
141 -0.996094   3.227327      0      0
99  -0.996094   2.137467      0      0
85  -0.937500   2.151968      0      0
97  -0.878906   2.149052      0      0
89  -0.878906   2.297125      0      0
0   -0.878906   2.623967      0      0
49  -0.878906   2.097885      0      0
92  -0.820312   1.978262      0      0
133 -0.585938   2.157824      3      0
16  -0.527344   2.077471      3      0
127 -0.527344   2.159503      3      0
55  -0.468750   3.034164      3      0
39  -0.468750   3.034164      3      0
3   -0.468750   2.641448      3      0
155 -0.410156   2.049097      3      0
148 -0.410156   3.317002      3      0
154 -0.410156   2.026653      3      0
5   -0.410156   2.735158      3      0
38  -0.351562   1.968790      3      0
6   -0.058594   2.319199     -1      1
40   0.175781   2.052886     10      0
31   0.175781   2.260640     10      0
26   0.644531   2.603049     -1      1
32   0.996094   2.771344     -1      1
25   1.347656   3.754483     -1      1
41   2.050781   2.221289      4      0
44   2.167969   4.224507      4  

In [143]:
left = np.zeros(df.shape[0], dtype=bool)

In [144]:
left[0] = 1

In [145]:
for i in range(1, df.shape[0]):
    _t = z0[i]

    if _t - z0[i - 1] > 0.15:
        left[i] = 1
    else:
        left[i] = 0

In [146]:
bound = np.zeros(df.shape[0])
noise = np.zeros(df.shape[0])

In [147]:
for i in range(df.shape[0] - 1):
    check1 = left[i] and not left[i + 1]
    check2 = not left[i] and left[i + 1]
    noise_check = left[i] and left[i + 1]
    if check1 or check2:
        bound[i] = i
    elif noise_check:
        bound[i] = -1
        noise[i] = 1
    else:
        bound[i] = df.shape[0]

    if left[df.shape[0] - 1]:
        bound[df.shape[0] - 1] = df.shape[0]
    else:
        bound[df.shape[0] - 1] = df.shape[0] - 1

In [148]:
df["noise_check"] = noise_check

In [149]:
df["bound"] = bound

In [150]:
df.head(20)

z0        pt  label  noise  noise_check  bound
67  -7.441406  2.149052     15      0        False   -1.0
140 -7.441406  2.573483     15      0        False   -1.0
76  -6.972656  3.295341     -1      1        False    2.0
153 -6.562500  3.295341     18      0        False    3.0
119 -6.503906  3.310079     18      0        False    4.0
135 -6.328125  2.251928     12      0        False    5.0
57  -6.328125  2.309069     12      0        False   -1.0
62  -6.269531  2.014883     12      0        False    7.0
43  -6.152344  3.104588     12      0        False    8.0
147 -6.035156  1.980026     12      0        False   -1.0
34  -5.332031  4.871437      9      0        False   -1.0
51  -5.214844  2.100663      9      0        False   11.0
27  -5.156250  3.778763      9      0        False   12.0
81  -5.039062  4.026843      9      0        False   13.0
126 -4.980469  2.308109      9      0        False   14.0
115 -4.921875  2.349133      9      0        False   15.0
29  -4.863281  1.959754      9      0        False  159.0
118 -4.453125  2.302843     -1      1        False   17.0
149 -4.218750  2.707806     14      0        False   18.0
60  -4.160156  2.195374     14      0        False   19.0

In [151]:
left

array([ True,  True,  True, False,  True, False,  True,  True, False,
        True,  True,  True, False,  True, False,  True, False, False,
        True, False,  True, False,  True,  True, False, False, False,
       False,  True, False,  True,  True,  True,  True, False,  True,
        True,  True, False, False,  True,  True,  True, False,  True,
        True, False,  True, False, False,  True, False,  True,  True,
       False, False, False, False,  True,  True, False,  True, False,
        True, False,  True, False, False,  True, False, False,  True,
       False,  True,  True, False, False,  True,  True, False, False,
       False,  True, False, False,  True, False, False,  True, False,
       False, False,  True, False,  True,  True, False,  True, False,
        True,  True, False, False,  True, False,  True, False,  True,
       False, False, False,  True, False, False, False, False,  True,
       False, False, False,  True, False, False,  True,  True, False,
       False,  True,

In [152]:
df["left"] = left

In [153]:
df.head()

z0        pt  label  noise  noise_check  bound   left
67  -7.441406  2.149052     15      0        False   -1.0   True
140 -7.441406  2.573483     15      0        False   -1.0   True
76  -6.972656  3.295341     -1      1        False    2.0   True
153 -6.562500  3.295341     18      0        False    3.0  False
119 -6.503906  3.310079     18      0        False    4.0   True

In [154]:
df["left"] = df["left"].astype(int)

In [155]:
df.reset_index(drop=True, inplace=True)

In [156]:
df[["z0", "noise", "left"]].head()

z0  noise  left
0 -7.441406      0     1
1 -7.441406      0     1
2 -6.972656      1     1
3 -6.562500      0     0
4 -6.503906      0     1

In [157]:
for i in range(df.shape[0]):
    if df["noise"][i] == 1:
        if i == 0:
            print("[x, " + str(df["left"][i]) + ", " + str(df["left"][i + 1]) + "]")
        elif i == df.shape[0] - 1:
            print(
                "[" + str(df["left"][i - 1]) + ", " + str(df["left"][i]) + ", " + "x]"
            )
        else:
            print(
                "["
                + str(df["left"][i - 1])
                + ", "
                + str(df["left"][i])
                + ", "
                + str(df["left"][i + 1])
                + "]"
            )
        # print(df['left'][i-1],df["left"][i], df['left'][i+1])

[1, 1, 0]
[0, 0, 1]
[0, 1, 1]
[0, 1, 0]
[1, 0, 1]
[0, 1, 1]
[1, 1, 0]
[1, 0, 0]
[1, 1, 0]
[0, 1, 0]
[1, 0, 1]
[0, 1, x]


# Use the standard function to generate the left boundaries

In [158]:
from acceleratedDBSCAN import AccDBSCAN

In [159]:
max_number_of_tracks = 232
max_number_of_tracks_power_2 = 256
max_number_of_tracks_log_2 = 8
eps = 0.15

In [160]:
db_acc = AccDBSCAN(z0, pt, eps, max_number_of_tracks, True)

In [161]:
db_acc.fit()

data padded
tracks built
prefix sum done
data initialized...
left boundaries found...
right boundaries found...
vertices found...
scan complete.


In [162]:
!ls -lhtr

total 23M
-rwxr-xr-x 1 lucas lucas 252K Jan 24 14:03  TracksPerPhiSector.png
-rwxr-xr-x 1 lucas lucas 376K Jan 24 14:03  TrackParameters.png
-rwxr-xr-x 1 lucas lucas 108K Jan 24 14:03  residuals.png
-rwxr-xr-x 1 lucas lucas 6.8K Jan 24 14:03  README.md
-rwxr-xr-x 1 lucas lucas 637K Jan 24 14:03  L1TriggerInputData.png
-rwxr-xr-x 1 lucas lucas 3.2K Jan 24 14:03  histograms.py
-rwxr-xr-x 1 lucas lucas 8.9K Jan 24 14:03  analysis.py
-rwxr-xr-x 1 lucas lucas  954 Jan 24 14:03  fasthisto_optimization.py
-rwxr-xr-x 1 lucas lucas 1.7K Jan 24 14:03  dbscan_optimization.py
-rwxr-xr-x 1 lucas lucas  921 Jan 24 14:03  convert_root_to_pickle.py
-rwxr-xr-x 1 lucas lucas 2.2K Jan 24 14:03  checkFastHisto.py
-rwxr-xr-x 1 lucas lucas 5.1K Jan 24 14:03  analyze_files.py
drwxr-xr-x 2 lucas lucas 4.0K Jan 24 14:03  plots
-rwxr-xr-x 1 lucas lucas  16K Mar 28 16:56  analyze_hdbscan.py
-rwxr-xr-x 1 lucas lucas  11K Apr 29 16:24  clusters.npy
-rw-rw-r-- 1 lucas lucas 2.5K May  3 13:35  boundaries.npy
-rw-rw-

In [163]:
left_acc = np.load("left_boundaries.npy")

In [164]:
left_acc.shape

(232,)

In [165]:
left_acc

array([ True, False,  True,  True, False,  True, False, False, False,
       False,  True, False, False, False, False, False, False,  True,
        True, False, False, False, False,  True, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False,  True,  True, False,  True,  True,
        True,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False,  True, False, False,  True,  True,
        True, False,

In [166]:
df.shape[0]

159

In [167]:
left_acc[0:139]

array([ True, False,  True,  True, False,  True, False, False, False,
       False,  True, False, False, False, False, False, False,  True,
        True, False, False, False, False,  True, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False,  True,  True, False,  True,  True,
        True,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False,  True, False, False,  True,  True,
        True, False,

In [186]:
df["left_acc"] = left_acc[0 : df.shape[0]]

In [187]:
df["left_acc"] = df["left_acc"].astype(int)

In [188]:
df

z0         pt  label  noise  noise_check  bound  left  left_acc
0   -7.441406   2.149052     15      0        False   -1.0     1         1
1   -7.441406   2.573483     15      0        False   -1.0     1         0
2   -6.972656   3.295341     -1      1        False    2.0     1         1
3   -6.562500   3.295341     18      0        False    3.0     0         1
4   -6.503906   3.310079     18      0        False    4.0     1         0
5   -6.328125   2.251928     12      0        False    5.0     0         1
6   -6.328125   2.309069     12      0        False   -1.0     1         0
7   -6.269531   2.014883     12      0        False    7.0     1         0
8   -6.152344   3.104588     12      0        False    8.0     0         0
9   -6.035156   1.980026     12      0        False   -1.0     1         0
10  -5.332031   4.871437      9      0        False   -1.0     1         1
11  -5.214844   2.100663      9      0        False   11.0     1         0
12  -5.156250   3.778763      9      0        False   12.0     0         0
13  -5.039062   4.026843      9      0        False   13.0     1         0
14  -4.980469   2.308109      9      0        False   14.0     0         0
15  -4.921875   2.349133      9      0        False   15.0     1         0
16  -4.863281   1.959754      9      0        False  159.0     0         0
17  -4.453125   2.302843     -1      1        False   17.0     0         1
18  -4.218750   2.707806     14      0        False   18.0     1         1
19  -4.160156   2.195374     14      0        False   19.0     0         0
20  -4.160156   2.499326     14      0        False   20.0     1         0
21  -4.101562   2.414004     14      0        False   21.0     0         0
22  -4.042969   2.229318     14      0        False   -1.0     1         0
23  -3.808594   2.410335      5      0        False   23.0     1         1
24  -3.750000   2.053645      5      0        False  159.0     0         0
25  -3.750000   2.604270      5      0        False  159.0     0         0
26  -3.691406   2.442685      5      0        False  159.0     0         0
27  -3.632812   4.641306      5      0        False   27.0     0         0
28  -3.632812   5.702108      5      0        False   28.0     1         0
29  -3.574219   2.190609      5      0        False   29.0     0         0
30  -3.515625   2.666188      5      0        False   -1.0     1         0
31  -3.281250   2.077082      8      0        False   -1.0     1         1
32  -3.222656   4.105771      8      0        False   -1.0     1         0
33  -3.164062   2.189745      8      0        False   33.0     1         0
34  -3.105469   2.812058      8      0        False   34.0     0         0
35  -3.046875   2.335789      8      0        False   -1.0     1         0
36  -3.046875   2.537021      8      0        False   -1.0     1         0
37  -3.046875   2.563973      8      0        False   37.0     1         0
38  -2.988281   3.104588      8      0        False  159.0     0         0
39  -2.988281   4.360568      8      0        False   39.0     0         0
40  -2.871094   2.206719      8      0        False   -1.0     1         0
41  -2.812500   2.332354      8      0        False   -1.0     1         0
42  -2.753906   2.232008      8      0        False   42.0     1         0
43  -2.753906   4.518521      8      0        False   43.0     0         0
44  -2.460938   2.997302     13      0        False   -1.0     1         1
45  -2.460938   2.185434     13      0        False   45.0     1         0
46  -2.402344   2.602439     13      0        False   46.0     0         0
47  -2.226562   2.978006      6      0        False   47.0     1         1
48  -2.167969   1.996763      6      0        False  159.0     0         0
49  -2.050781   2.006870      6      0        False   49.0     0         0
50  -1.992188   2.202342      6      0        False   50.0     1         0
51  -1.992188   4.492920      6      0        False   51.0     0         0
52  -1.992188   2.014883      6     

In [189]:
df[["z0", "noise", "left", "left_acc"]].head(20)

z0  noise  left  left_acc
0  -7.441406      0     1         1
1  -7.441406      0     1         0
2  -6.972656      1     1         1
3  -6.562500      0     0         1
4  -6.503906      0     1         0
5  -6.328125      0     0         1
6  -6.328125      0     1         0
7  -6.269531      0     1         0
8  -6.152344      0     0         0
9  -6.035156      0     1         0
10 -5.332031      0     1         1
11 -5.214844      0     1         0
12 -5.156250      0     0         0
13 -5.039062      0     1         0
14 -4.980469      0     0         0
15 -4.921875      0     1         0
16 -4.863281      0     0         0
17 -4.453125      1     0         1
18 -4.218750      0     1         1
19 -4.160156      0     0         0

In [205]:
col = "left_acc"

for i in range(df.shape[0]):
    if df["noise"][i] == 1:
        if i == 0:
            print("N: [x, " + str(df[col][i]) + ", " + str(df[col][i + 1]) + "]")
        elif i == df.shape[0] - 1:
            print("N: [" + str(df[col][i - 1]) + ", " + str(df[col][i]) + ", " + "x]")
        else:
            print(
                "N: ["
                + str(df[col][i - 1])
                + ", "
                + str(df[col][i])
                + ", "
                + str(df[col][i + 1])
                + "]"
            )
        # print(df['left'][i-1],df["left"][i], df['left'][i+1])
    else:
        if i == 0:
            print("C: [x, " + str(df[col][i]) + ", " + str(df[col][i + 1]) + "]")
        elif i == df.shape[0] - 1:
            print("C: [" + str(df[col][i - 1]) + ", " + str(df[col][i]) + ", " + "x]")
        else:
            print(
                "C: ["
                + str(df[col][i - 1])
                + ", "
                + str(df[col][i])
                + ", "
                + str(df[col][i + 1])
                + "]"
            )

C: [x, 1, 0]
C: [1, 0, 1]
N: [0, 1, 1]
C: [1, 1, 0]
C: [1, 0, 1]
C: [0, 1, 0]
C: [1, 0, 0]
C: [0, 0, 0]
C: [0, 0, 0]
C: [0, 0, 1]
C: [0, 1, 0]
C: [1, 0, 0]
C: [0, 0, 0]
C: [0, 0, 0]
C: [0, 0, 0]
C: [0, 0, 0]
C: [0, 0, 1]
N: [0, 1, 1]
C: [1, 1, 0]
C: [1, 0, 0]
C: [0, 0, 0]
C: [0, 0, 0]
C: [0, 0, 1]
C: [0, 1, 0]
C: [1, 0, 0]
C: [0, 0, 0]
C: [0, 0, 0]
C: [0, 0, 0]
C: [0, 0, 0]
C: [0, 0, 0]
C: [0, 0, 1]
C: [0, 1, 0]
C: [1, 0, 0]
C: [0, 0, 0]
C: [0, 0, 0]
C: [0, 0, 0]
C: [0, 0, 0]
C: [0, 0, 0]
C: [0, 0, 0]
C: [0, 0, 0]
C: [0, 0, 0]
C: [0, 0, 0]
C: [0, 0, 0]
C: [0, 0, 1]
C: [0, 1, 0]
C: [1, 0, 0]
C: [0, 0, 1]
C: [0, 1, 0]
C: [1, 0, 0]
C: [0, 0, 0]
C: [0, 0, 0]
C: [0, 0, 0]
C: [0, 0, 0]
C: [0, 0, 0]
C: [0, 0, 0]
C: [0, 0, 0]
C: [0, 0, 0]
C: [0, 0, 0]
C: [0, 0, 0]
C: [0, 0, 0]
C: [0, 0, 0]
C: [0, 0, 0]
C: [0, 0, 0]
C: [0, 0, 0]
C: [0, 0, 0]
C: [0, 0, 1]
C: [0, 1, 0]
C: [1, 0, 0]
C: [0, 0, 0]
C: [0, 0, 0]
C: [0, 0, 0]
C: [0, 0, 0]
C: [0, 0, 0]
C: [0, 0, 0]
C: [0, 0, 0]
C: [0, 0, 0]
C: [0, 0, 0]

In [191]:
for i in range(df.shape[0] - 1):
    l1 = df[col][i]
    l2 = df[col][i + 1]

    if (l1 == 1) and (l2 == 1):
        print(df["noise"][i])

1
1
1
1
1
1
1
1
1
1
1


In [192]:
max_tracks = 5

In [193]:
boundaries = np.zeros((max_tracks, 1))

In [194]:
for i in range(max_tracks - 1):
    print(i)

0
1
2
3


In [195]:
boundaries[3]

array([0.])

In [196]:
a = np.array([2, 1, 4, 3])
b = np.array([1, 2, 3, 4])

In [197]:
idx = a.argsort()

In [198]:
a[idx]

array([1, 2, 3, 4])

In [199]:
b[idx]

array([2, 1, 4, 3])

In [200]:
idx

array([1, 0, 3, 2])

In [201]:
np.argmax(a)

2

In [202]:
a[np.argmax(a)]

4

In [203]:
df

z0         pt  label  noise  noise_check  bound  left  left_acc
0   -7.441406   2.149052     15      0        False   -1.0     1         1
1   -7.441406   2.573483     15      0        False   -1.0     1         0
2   -6.972656   3.295341     -1      1        False    2.0     1         1
3   -6.562500   3.295341     18      0        False    3.0     0         1
4   -6.503906   3.310079     18      0        False    4.0     1         0
5   -6.328125   2.251928     12      0        False    5.0     0         1
6   -6.328125   2.309069     12      0        False   -1.0     1         0
7   -6.269531   2.014883     12      0        False    7.0     1         0
8   -6.152344   3.104588     12      0        False    8.0     0         0
9   -6.035156   1.980026     12      0        False   -1.0     1         0
10  -5.332031   4.871437      9      0        False   -1.0     1         1
11  -5.214844   2.100663      9      0        False   11.0     1         0
12  -5.156250   3.778763      9      0        False   12.0     0         0
13  -5.039062   4.026843      9      0        False   13.0     1         0
14  -4.980469   2.308109      9      0        False   14.0     0         0
15  -4.921875   2.349133      9      0        False   15.0     1         0
16  -4.863281   1.959754      9      0        False  159.0     0         0
17  -4.453125   2.302843     -1      1        False   17.0     0         1
18  -4.218750   2.707806     14      0        False   18.0     1         1
19  -4.160156   2.195374     14      0        False   19.0     0         0
20  -4.160156   2.499326     14      0        False   20.0     1         0
21  -4.101562   2.414004     14      0        False   21.0     0         0
22  -4.042969   2.229318     14      0        False   -1.0     1         0
23  -3.808594   2.410335      5      0        False   23.0     1         1
24  -3.750000   2.053645      5      0        False  159.0     0         0
25  -3.750000   2.604270      5      0        False  159.0     0         0
26  -3.691406   2.442685      5      0        False  159.0     0         0
27  -3.632812   4.641306      5      0        False   27.0     0         0
28  -3.632812   5.702108      5      0        False   28.0     1         0
29  -3.574219   2.190609      5      0        False   29.0     0         0
30  -3.515625   2.666188      5      0        False   -1.0     1         0
31  -3.281250   2.077082      8      0        False   -1.0     1         1
32  -3.222656   4.105771      8      0        False   -1.0     1         0
33  -3.164062   2.189745      8      0        False   33.0     1         0
34  -3.105469   2.812058      8      0        False   34.0     0         0
35  -3.046875   2.335789      8      0        False   -1.0     1         0
36  -3.046875   2.537021      8      0        False   -1.0     1         0
37  -3.046875   2.563973      8      0        False   37.0     1         0
38  -2.988281   3.104588      8      0        False  159.0     0         0
39  -2.988281   4.360568      8      0        False   39.0     0         0
40  -2.871094   2.206719      8      0        False   -1.0     1         0
41  -2.812500   2.332354      8      0        False   -1.0     1         0
42  -2.753906   2.232008      8      0        False   42.0     1         0
43  -2.753906   4.518521      8      0        False   43.0     0         0
44  -2.460938   2.997302     13      0        False   -1.0     1         1
45  -2.460938   2.185434     13      0        False   45.0     1         0
46  -2.402344   2.602439     13      0        False   46.0     0         0
47  -2.226562   2.978006      6      0        False   47.0     1         1
48  -2.167969   1.996763      6      0        False  159.0     0         0
49  -2.050781   2.006870      6      0        False   49.0     0         0
50  -1.992188   2.202342      6      0        False   50.0     1         0
51  -1.992188   4.492920      6      0        False   51.0     0         0
52  -1.992188   2.014883      6     